export const ProvidersConstants = {
  EVENT_STORE_PROVIDER: 'EVENT_STORE_PROVIDER',
  EVENT_STORE_STREAM_CONFIG_PROVIDER: 'EsStreamConfig',
  EVENT_STORE_CONNECTION_CONFIG_PROVIDER: 'EsConnectionConfig'
};

export const NEST_EVENTSTORE_OPTION = 'NEST_EVENTSTORE_OPTION';

export const NEST_EVENTSTORE_FEATURE_OPTION = 'NEST_EVENTSTORE_FEATURE_OPTION';

export const NEST_EVENTSTORE_MODULE_ID = 'NEST_EVENTSTORE_MODULE_ID';
export const EVENT_STORE_CONFIG = 'EVENT_STORE_CONFIG';

export const EVENT_STORE_STORAGE_ADAPTER = 'EVENT_STORE_STORAGE_ADAPTER';
